// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRxlHTdmov0rb_AQg9Q-podEzOFoqQjL0',
    appId: '1:694075691841:web:d27356ceb65c8accb447c0',
    messagingSenderId: '694075691841',
    projectId: 'smartfarmbayam',
    authDomain: 'smartfarmbayam.firebaseapp.com',
    storageBucket: 'smartfarmbayam.firebasestorage.app',
    measurementId: 'G-WFDJD8HY6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvMJlHBeVkXnbHEcPmkUGMuYekWH9VBdE',
    appId: '1:694075691841:android:049e4511ac1a0a40b447c0',
    messagingSenderId: '694075691841',
    projectId: 'smartfarmbayam',
    storageBucket: 'smartfarmbayam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3JfZ287eHfyxrL2EABg_4bS8cO6XsQw',
    appId: '1:694075691841:ios:e4e2b2646b788ce1b447c0',
    messagingSenderId: '694075691841',
    projectId: 'smartfarmbayam',
    storageBucket: 'smartfarmbayam.firebasestorage.app',
    iosClientId:
        '694075691841-nnt9kv8jklub44fpkhjpshpr877c8nsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarmBayam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3JfZ287eHfyxrL2EABg_4bS8cO6XsQw',
    appId: '1:694075691841:ios:e4e2b2646b788ce1b447c0',
    messagingSenderId: '694075691841',
    projectId: 'smartfarmbayam',
    storageBucket: 'smartfarmbayam.firebasestorage.app',
    iosClientId:
        '694075691841-nnt9kv8jklub44fpkhjpshpr877c8nsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarmBayam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRxlHTdmov0rb_AQg9Q-podEzOFoqQjL0',
    appId: '1:694075691841:web:11d682547cc71a7db447c0',
    messagingSenderId: '694075691841',
    projectId: 'smartfarmbayam',
    authDomain: 'smartfarmbayam.firebaseapp.com',
    storageBucket: 'smartfarmbayam.firebasestorage.app',
    measurementId: 'G-S9XLK1F66C',
  );
}
